### ISSUE TITLE
Support multi-valued sbatch argument

### ISSUE THREAD

**Issue by tristan0x** [BlueBrain/hpcbench#224]
for instance:

```yaml
process:
  type: slurm
  sbatch:
    mail-type: ALL
    mail-user:
    - john.doe@acme.com
    - johnny.begood@acme.com
```

This is not blocker, because in this particular case `mail-user` supports a comma-separated list of email addresses.
