### ISSUE TITLE
Improve OSU benchmark options

### ISSUE THREAD

**Issue by tristan0x** [BlueBrain/hpcbench#284]
Here is a current valid campaign invoking osu:
```yaml
benchmarks:
  \*:
    test:
     type: osu
     arguments:
       categories: [osu_bw, osu_latency]
       arguments:
         osu_bw: [-x, 200, -i, 100]
         osu_latency: [-x, 200, -i, 400]
```

This issue describes a set of changes to the `arguments` parameter of osu benchmark

* rename `arguments` to `options` to remove confusion with `arguments` key at top-level. Previous campaign file should still be usable: If `options` is not set but `arguments` is, then hpcbench should raise a warning but still take `arguments` into account. for instance:
    ```yaml
    benchmarks:
      \*:
        test:
         type: osu
         arguments:
           categories: [osu_bw, osu_latency]
           options:
             osu_bw: [-x, 200, -i, 100]
             osu_latency: [-x, 200, -i, 400]
    ```

* allow partial override of `options` (formally `arguments`) i.e user should not have to specify options of all categories when he only wants to customise one, for instance:
    ```yaml
    benchmarks:
      \*:
        test:
         type: osu
         arguments:
           categories: [osu_bw, osu_latency]
           options:
             osu_bw: [-x, 200, -i, 100]
    ```

* if value is a list instead of a dict, then it is used for all categories, for instance:
    ```yaml
    benchmarks:
      \*:
        test:
         type: osu
         arguments:
           categories: [osu_bw, osu_latency]
           arguments: [-x, 200, -i, 100]
    ```
